export enum routes {
  DASHBOARD = '/dashboard',
  TYPOGRAPHY = '/typography',
  CATEGORIA = '/categoria',
  CLIENTE = '/cliente',
  FUNCIONARIO = '/funcionario',
  PRODUTO = '/produto',
  PROMOCAO = '/promocao',
  PONTUACAO = '/pontuacao',
  RESGATE = '/resgate',
  TABLES = '/tables',
  HOMECLIENTE = '/homecliente',
  HOMEFUNCIONARIO = '/homefuncionario',
  NOTIFICATION = '/notification',
  UI_ELEMENTS_ICONS = '/ui/icons',
  UI_ELEMENTS_CHARTS = '/ui/charts',
  UI_ELEMENTS_MAP = '/ui/map',
  LOGIN = '/login',
  SOBRE = '/sobre'
}
